name: C++ Test Challenge CI

on:
  push:
    paths:
      - 'cpp/test_challenge/**'
      - 'cpp/CMakeLists.txt'
  pull_request:
    paths:
      - 'cpp/test_challenge/**'
      - 'cpp/CMakeLists.txt'

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake g++ libgtest-dev

      - name: Configure CMake
        run: |
          cmake -S cpp -B cpp/build

      - name: Build
        run: |
          cmake --build cpp/build

      - name: Run tests
        working-directory: cpp/build
        run: |
          ctest --output-on-failure
