name: C++ Test Challenge CI

on:
  push:
    paths:
      - 'cpp/test_challenge/**'

defaults:
  run:
    shell: bash
    working-directory: ./cpp/test_challenge


jobs:
  test:
    runs-on: ubuntu-latest
    env:
      GKSS_LEADERBOARD_API_KEY: ${{ secrets.GKSS_LEADERBOARD_API_KEY }}
      GKSS_LEADERBOARD_API_URL: ${{ secrets.GKSS_LEADERBOARD_API_URL }}
    steps:
      - uses: actions/checkout@v4
      
      - name: Build solution
        uses: threeal/cmake-action@v2
        with:
          build-dir: ci-build

      - name: Run tests
        working-directory: ci-build/
        run: |
          ctest --output-on-failure
